author: snowdrop # 作者
description: bolg
keyword: vuejs
favicon: 
title: snowdrop
logoTitle: FE

excerpt_link: Read more

menu:
 首页: /
 标签: /tags/
 归档: /archives/
 开源项目: /project/
 关于: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: true

# comment
# you can set gitment or uyan


comment: gitment

# gitment config
gitment_owner: KuangPF
gitment_repo: bolg
gitment_oauth_id: 52d34cfe84bdd73cf53a
gitment_oauth_secret: 72fa5c33a1748a7c3b770146922c87a5531c9933


# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars2.githubusercontent.com/u/20694238?s=460&v=4
  description: 其实，敲代码不是爱好，也许...
  # Links
	segmentfault_username: snowlotus
  home_url: https://snowlotus.github.io
  weibo_username: snowlotus
  facebook_username: snowlotus
  github_username: snowlotus
  zhihu_username: KuangPF
  mail_username: cgi-bin/qm_share?t=qm_mailme&email=qpucmZmZk52Ykpzq29uEycXH